package com.Wsdl2Code.WebServices.MobileWebserviceImplService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/21/2016 11:56:15 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class deviceTO implements KvmSerializable {
    
    public String androidUuid;
    public int id;
    public String username;
    
    public deviceTO(){}
    
    public deviceTO(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("androidUuid"))
        {
            Object obj = soapObject.getProperty("androidUuid");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                androidUuid = j.toString();
            }else if (obj!= null && obj instanceof String){
                androidUuid = (String) obj;
            }
        }
        if (soapObject.hasProperty("id"))
        {
            Object obj = soapObject.getProperty("id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                id = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                id = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("username"))
        {
            Object obj = soapObject.getProperty("username");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                username = j.toString();
            }else if (obj!= null && obj instanceof String){
                username = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return androidUuid;
            case 1:
                return id;
            case 2:
                return username;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "androidUuid";
                break;
            case 1:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "id";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "username";
                break;
        }
    }

    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
